#pragma once
#include "glm/glm.hpp"
#include <iostream>
#include <list>
#include <cmath>
#include <algorithm>
#include <utility>
#include <math.h>
#include <vector>
#include <iomanip>
#include <iterator>
#include <fstream>